version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - ./build
      - attach_workspace:
          at: .
      - aws-s3/sync:
          from: build
          to: 's3://testci-monstergelo/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true
workflows:
    build-and-test:
      jobs:
        - build-and-test

